CREATE TABLE "visitor_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"ip" text DEFAULT '' NOT NULL,
	"path" text DEFAULT '' NOT NULL,
	"referer" text DEFAULT '' NOT NULL,
	"country_code" text DEFAULT '' NOT NULL,
	"country_name" text DEFAULT '' NOT NULL,
	"continent_code" text DEFAULT '' NOT NULL,
	"continent_name" text DEFAULT '' NOT NULL,
	"registered_country_code" text DEFAULT '' NOT NULL,
	"registered_country_name" text DEFAULT '' NOT NULL,
	"city_name" text DEFAULT '' NOT NULL,
	"region_name" text DEFAULT '' NOT NULL,
	"time_zone" text DEFAULT '' NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"autonomous_system_number" integer,
	"autonomous_system_organization" text DEFAULT '' NOT NULL,
	"rir" text DEFAULT '' NOT NULL,
	"is_anonymous" boolean DEFAULT false NOT NULL,
	"is_anonymous_vpn" boolean DEFAULT false NOT NULL,
	"is_hosting_provider" boolean DEFAULT false NOT NULL,
	"is_public_proxy" boolean DEFAULT false NOT NULL,
	"is_tor_exit_node" boolean DEFAULT false NOT NULL,
	"browser_name" text DEFAULT '' NOT NULL,
	"browser_version" text DEFAULT '' NOT NULL,
	"os_name" text DEFAULT '' NOT NULL,
	"os_version" text DEFAULT '' NOT NULL,
	"device_type" text DEFAULT '' NOT NULL,
	"device_vendor" text DEFAULT '' NOT NULL,
	"device_model" text DEFAULT '' NOT NULL,
	"engine_name" text DEFAULT '' NOT NULL,
	"engine_version" text DEFAULT '' NOT NULL,
	"cpu_architecture" text DEFAULT '' NOT NULL,
	"user_agent" text DEFAULT '' NOT NULL,
	"accept_language" text DEFAULT '' NOT NULL,
	"geo_raw" jsonb,
	"user_agent_raw" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
